services:
  php5.6:
    build:
      context: ./php
      dockerfile: Dockerfile.php56
      args:
        USER_SO_ID: ${USER_SO_ID}
        USER_SO_NAME: ${USER_SO_NAME}
    container_name: php5.6
    restart: always
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network
  php7.3:
    build:
      context: ./php
      dockerfile: Dockerfile.php73
      args:
        USER_SO_ID: ${USER_SO_ID}
        USER_SO_NAME: ${USER_SO_NAME}
    container_name: php7.3
    restart: always
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network

  php7.4:
    build:
      context: ./php
      dockerfile: Dockerfile.php74
      args:
        USER_SO_ID: ${USER_SO_ID}
        USER_SO_NAME: ${USER_SO_NAME}
    container_name: php7.4
    restart: always
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network
    #ports:
      #- "9000:9000" # Puerto para PHP-FPM
      #- "9003:9003" # Puerto para Xdebug
      #- "44895:44895"

  php8.2:
    build:
      context: ./php
      dockerfile: Dockerfile.php82
      args:
        USER_SO_ID: ${USER_SO_ID}
        USER_SO_GID: ${USER_SO_ID}
        USER_SO_NAME: ${USER_SO_NAME}
    user: "1000:1000"
    container_name: php8.2
    restart: always
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - ./www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
      #- "9000:9000"
    depends_on:
      - php8.2
      - php7.4
      #- php74.16
      - php7.3
      # - php5.6
    networks:
      - develop-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SQL_MODE: "NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - develop-network
    ports:
      - "3306:3306"

volumes:
  mysql-data:

networks:
  develop-network:
    driver: bridge
