version: '3.8'

services:
  php5.6:
    build:
      context: ./php
      dockerfile: Dockerfile.php56
    container_name: php5.6
    restart: always
    volumes:
      - ./projects:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network
  php7.3:
    build:
      context: ./php
      dockerfile: Dockerfile.php73
    container_name: php7.3
    restart: always
    volumes:
      - ./projects:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network

  php7.4:
    build:
      context: ./php
      dockerfile: Dockerfile.php74
    container_name: php7.4
    restart: always
    volumes:
      - ./projects:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network

  php8.2:
    build:
      context: ./php
      dockerfile: Dockerfile.php82
    container_name: php8.2
    restart: always
    volumes:
      - ./projects:/var/www
    depends_on:
      - mysql
    # environment:
      # - "DB_CONNECTION=mysql"
      # - "DB_HOST=mysql"
      # - "DB_PORT=3306"
    networks:
      - develop-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - php8.2
      - php7.4
      - php7.3
      - php5.6
    networks:
      - develop-network

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - develop-network

volumes:
  mysql-data:

networks:
  develop-network:
    driver: bridge
