#!/bin/bash

# Verifica si se pasó un argumento
if [ -z "$1" ]; then
    echo "Uso: cdev <nombre_del_contenedor>"
    exit 1
fi

#Si el comando es nginx entonces, ejecutar: docker exec nginx nginx $2 $3
if [ "$1" == "nginx" ]; then
    # Verifica si se pasaron suficientes argumentos
    if [ -z "$2" ]; then
        echo "Uso: cdev nginx <argumento_2> [<argumento_3>]"
        exit 1
    fi

    # Ejecuta el comando con los argumentos proporcionados
    if [ -n "$3" ]; then
        # Se proporcionan argumentos 2 y 3
        docker exec nginx nginx "$2" "$3"
    else
        # Solo se proporciona argumento 2
        docker exec nginx nginx "$2"
    fi
    exit
fi

# Obtiene la ruta actual
current_path=$(pwd)

# Extrae la parte de la ruta que empieza desde "/www/"
target_path=${current_path#*/www/}

# Si el path resultante está vacío, usar solo "/www/"
if [ -z "$target_path" ]; then
    target_path="/var/www"
else
    target_path="/var/www/$target_path"
fi

# Ejecuta el comando docker exec con la ruta del directorio
docker exec -it "$1" bash -c "cd '$target_path' && exec bash"

